### ISSUE TITLE
Github Releasesの作成願い

### ISSUE THREAD

**Issue by ttakayuki** [aistairc/trf#24]
AIST AIRC Githubリポジトリをご利用の皆様。

作成されたソフトウェアの利用状況把握のため、Github Releasesの作成をお願いします。

## Github Releases作成手順

1. Githubのリポジトリページを開く。
2. リポジトリ名下にある "release" をクリックする。
3. "Draft a new release" をクリックし、タグバージョン等を入力する。
   * Tag version: "タグ"
   * Target: "ブランチ"
   * Release title: "タイトル"
   * Description: "リリースノート等、リリースの説明文"
4. 他にバイナリ形式の成果物などがあれば"Attach binaries by dropping them here or selecting them." のエリアから追加する。
5. 設定後、"Publish release" をクリックする。

詳しくは以下のURLをご参照ください。

* https://help.github.com/articles/creating-releases/

**Comment by pecorarista** [comment]
対応しました
